finalProject-12/finalproject-12BE

src/main/java/com/example/finalproject12be/common/ResponseMsgDto.java, src/main/java/com/example/finalproject12be/common/Timestamped.java, src/main/java/com/example/finalproject12be/domain/comment/controller/CommentController.java, src/main/java/com/example/finalproject12be/domain/comment/dto/CommentRequestDto.java, src/main/java/com/example/finalproject12be/domain/comment/dto/CommentResponseDto.java, src/main/java/com/example/finalproject12be/domain/comment/entity/Comment.java, src/main/java/com/example/finalproject12be/domain/comment/repository/CommentRepository.java, src/main/java/com/example/finalproject12be/domain/comment/service/CommentService.java
댓글 생성 같은 경우 201번 코드와 출력메세지를 api명세서에
맞춰 내려주려고 두가지로 코딩해서 주석처리해놓음
=> Feat : 댓글 기능 구현

src/main/java/com/example/finalproject12be/domain/member/entity/Member.java, src/main/java/com/example/finalproject12be/exception/CommonErrorCode.java, src/main/java/com/example/finalproject12be/exception/ErrorResponse.java, src/main/java/com/example/finalproject12be/exception/GlobalExceptionHandler.java, src/main/java/com/example/finalproject12be/exception/MemberErrorCode.java, src/main/java/com/example/finalproject12be/exception/RestApiException.java
일단 모든 커스텀 에러 코드들을 모두 가져왔습니다. 사용되지 않는 에러 코드들은 후에 리팩토링을 거쳐 삭제하겠습니다.
=> Feat: GlobalExceptionHandler 추가

src/main/java/com/example/finalproject12be/domain/bookmark/controller/BookmarkController.java, src/main/java/com/example/finalproject12be/domain/bookmark/entity/Bookmark.java, src/main/java/com/example/finalproject12be/domain/bookmark/repository/BookmarkRepository.java, src/main/java/com/example/finalproject12be/domain/bookmark/service/BookmarkService.java, src/main/java/com/example/finalproject12be/domain/member/entity/Member.java, src/main/java/com/example/finalproject12be/domain/store/entity/Store.java
임시적인 기능 작동을 우선으로 해서 리팩토링 할 코드들이 많습니다.
후에 깔끔하게 고치겠습니다.
=> Feat: 북마크 작성 기능 추가

src/main/java/com/example/finalproject12be/config/WebSecurityConfig.java, src/main/java/com/example/finalproject12be/domain/comment/dto/CommentResponseDto.java
=> Fix : merge test

src/main/java/com/example/finalproject12be/domain/oauth/service/OauthMemberService.java
=> Feat : 카카오 소셜 로그인 기능 구현

src/main/java/com/example/finalproject12be/config/WebSecurityConfig.java
- JwtUtil 클래스에서 노출되어야 하는 ACCESS_KEY와 REFRESH_KEY를 CorsConfiguration에 추가하는 설정을 구현하였습니다.
=> feat: JwtUtil의 ACCESS_KEY와 REFRESH_KEY 노출 설정 추가

src/main/java/com/example/finalproject12be/domain/store/service/StoreService.java
여전히 기능 구현을 우선으로 해 코드가 읽기 어렵습니다 .. 시간 여유 남을 때 바로 리팩토링 후 리뷰 하겠습니다 !
=> FEAT: 검색, 필터링 시 북마크 기능 확인 로직 추가

src/main/java/com/example/finalproject12be/domain/oauth/controller/OauthController.java, src/main/java/com/example/finalproject12be/domain/oauth/service/OauthMemberService.java
- 소셜 로그인 시, ACCESS, REFRESH 토큰 헤더에 추가
=> feat: 카카오 소셜 로그인 기능 구현 

src/main/java/com/example/finalproject12be/domain/comment/controller/CommentController.java, src/main/java/com/example/finalproject12be/domain/comment/dto/CommentResponseDto.java, src/main/java/com/example/finalproject12be/domain/comment/repository/CommentRepository.java, src/main/java/com/example/finalproject12be/domain/comment/service/CommentService.java
마이페이지에서 본인이 쓴 댓글 리스트를 조회하는 로직 구현
=> Feat : 마이페이지 댓글 조회

src/main/java/com/example/finalproject12be/domain/comment/controller/CommentController.java
프론트에서 url에 memberId PK값을 이용하기에
오버코딩이라 Pathvariable 방식 사용 안하게 변경
=> Fix : 마이페이지 댓글 조회 url 변경

src/main/java/com/example/finalproject12be/domain/comment/controller/CommentController.java, src/main/java/com/example/finalproject12be/domain/comment/dto/CommentResponseDto.java, src/main/java/com/example/finalproject12be/domain/comment/service/CommentService.java
프론트에서 마이페이지에 필요한 정보 추가로 내려주기위해
수정
=> Fix : 마이페이지 댓글 조회 로직 수정

src/main/java/com/example/finalproject12be/domain/oauth/service/OauthMemberService.java
- KakaoMemberInfoRequest 생성자 매개변수 순서 변경
=> feat: 카카오 소셜 로그인 기능 구현

src/main/java/com/example/finalproject12be/domain/oauth/service/OauthMemberService.java, src/main/java/com/example/finalproject12be/domain/store/controller/StoreController.java, src/main/java/com/example/finalproject12be/domain/store/service/StoreService.java, src/main/java/com/example/finalproject12be/security/jwt/JwtUtil.java
- access token은 1분
- refresh token은 3분
=> feat: 테스트를 위한 토큰 만료 시간 수정

src/main/java/com/example/finalproject12be/domain/store/controller/StoreController.java, src/main/java/com/example/finalproject12be/domain/store/dto/ForeignOneStoreResponse.java, src/main/java/com/example/finalproject12be/domain/store/dto/ForeignStoreResponse.java, src/main/java/com/example/finalproject12be/domain/store/repository/StoreRepository.java, src/main/java/com/example/finalproject12be/domain/store/service/StoreService.java
유리님이 급하게 테스트 원하셔서 중복 코드도 많고 쿼리 DSL도 쓰이지 않았습니다 ! 후에 리팩토링 하겠습니다.
=> Feat: 외국어 약국 검색 기능 추가

src/main/java/com/example/finalproject12be/domain/oauth/service/OauthMemberService.java
=> feat: 소셜 로그인 로직 수정

src/main/java/com/example/finalproject12be/domain/member/controller/MemberController.java, src/main/java/com/example/finalproject12be/domain/oauth/service/OauthMemberService.java
=> feat: 소셜 계정 로그인 테스트 위한 redirect_uri 변경

src/main/java/com/example/finalproject12be/domain/member/service/MemberService.java, src/main/java/com/example/finalproject12be/domain/oauth/service/OauthMemberService.java
- 소셜 계정으로 회원 가입 시, 랜덤 닉네임 부여
- 소셜 계정 탈퇴 로직
=> feat: 소셜 로그인 및 회원가입 로직 추가

src/main/java/com/example/finalproject12be/domain/store/dto/ForeignOneStoreResponse.java, src/main/java/com/example/finalproject12be/domain/store/dto/OneStoreResponseDto.java
약국 상세보기 시 토요일, 일요일, 공휴일 반환 값 다음과 같이 수정
"토 NN:NN ~ NN:NN" -> "NN:NN ~ NN:NN""
=> Refactor: 약국 상세보기 반환 값 수정

src/main/java/com/example/finalproject12be/domain/member/controller/MemberController.java, src/main/java/com/example/finalproject12be/domain/member/dto/request/MemberValidNumberRequest.java, src/main/java/com/example/finalproject12be/domain/member/service/EmailService.java, src/main/java/com/example/finalproject12be/domain/member/service/MemberService.java, src/main/java/com/example/finalproject12be/domain/store/service/StoreService.java, src/main/java/com/example/finalproject12be/domain/validNumber/entity/ValidNumber.java, src/main/java/com/example/finalproject12be/domain/validNumber/repository/ValidNumberRepository.java
Feat: 이메일 인증 및 인증번호 검사 로직 구현 + 
Fix: 주말에 영업 중 필터 버그 해결
=> Feat: 이메일 인증 + Fix: 영업 중 필터 버그

src/main/java/com/example/finalproject12be/domain/comment/entity/Comment.java, src/main/java/com/example/finalproject12be/domain/comment/repository/CommentRepository.java, src/main/java/com/example/finalproject12be/domain/member/entity/Member.java, src/main/java/com/example/finalproject12be/domain/member/service/MemberService.java, src/main/java/com/example/finalproject12be/domain/oauth/service/OauthMemberService.java, src/main/java/com/example/finalproject12be/exception/MemberErrorCode.java
- 약국 생성, 수정, 삭제
- 댓글 수정, 삭제
- 회원 수정, 삭제
- 공지사항 CRUD 구현중
=> feat: 관리자 권한 기능 구현, 탈퇴한 회원 댓글 보존 처리 완료

src/main/java/com/example/finalproject12be/domain/member/service/MemberService.java, src/main/java/com/example/finalproject12be/domain/validNumber/entity/ValidNumber.java
기존 분 단위로 계산하는 로직 초 단위로 계산하는 로직으로 변경
=> Fix: 이메일 인증번호 3분 초과 시 에러

src/main/java/com/example/finalproject12be/domain/board/controller/BoardController.java, src/main/java/com/example/finalproject12be/domain/board/dto/BoardDetailResponse.java, src/main/java/com/example/finalproject12be/domain/board/dto/BoardResponse.java, src/main/java/com/example/finalproject12be/domain/board/entity/Board.java, src/main/java/com/example/finalproject12be/domain/board/repository/BoardRepository.java, src/main/java/com/example/finalproject12be/domain/board/service/BoardService.java, src/main/java/com/example/finalproject12be/domain/member/service/MemberService.java
=> feat : 공지사항 API 수정

src/main/java/com/example/finalproject12be/domain/store/controller/StoreController.java, src/main/java/com/example/finalproject12be/domain/store/service/StoreService.java
설명 주석 추가 및 필요 없는 주석 삭제
가독성 좋게 코드 정리
=> Comment: Store - controller, service

src/main/java/com/example/finalproject12be/domain/member/service/MemberService.java, src/main/java/com/example/finalproject12be/exception/ValidNumberErrorCode.java
- 인증번호를 찾을 수 없을 시 (CommonErrorCode.INVALID_REQUEST_PARAMETER)
- 만료 시간 3분이 지났을 시 (ValidNumberErrorCode.VALID_TIME_OVER)
- 틀린 인증번호일 시 (ValidNumberErrorCode.WRONG_NUMBER)
=> Fix: 이메일 인증번호 틀릴 시 에러코드 각자 다르게 반환

src/main/java/com/example/finalproject12be/domain/member/service/EmailService.java
kmskes0917@naver.com -> odimedi@naver.com
=> Fix: 이메일 전송 계정 수정

src/main/java/com/example/finalproject12be/domain/board/service/BoardService.java, src/main/java/com/example/finalproject12be/domain/member/controller/MemberController.java, src/main/java/com/example/finalproject12be/domain/member/entity/RefreshToken.java, src/main/java/com/example/finalproject12be/domain/member/repository/RefreshTokenRepository.java, src/main/java/com/example/finalproject12be/domain/member/service/MemberService.java, src/main/java/com/example/finalproject12be/domain/oauth/service/OauthMemberService.java, src/main/java/com/example/finalproject12be/exception/BoardErrorCode.java, src/main/java/com/example/finalproject12be/exception/MemberErrorCode.java
- 소셜 계정 회원 가입시, 이메일 제공 미동의 케이스에 대하여 임의 이메일 부여
=> feat. 소셜 계정 회원가입 로직 수정

src/main/java/com/example/finalproject12be/security/jwt/JwtUtil.java
=> feat : refresh 토큰 만료시간 변경

src/main/java/com/example/finalproject12be/domain/store/service/StoreService.java
내 위치, 약국 이름, 구 모두 선택 없으면 빈 배열 보내기
=> Fix: 약국 검색 기능 반환 수정

src/main/java/com/example/finalproject12be/domain/store/dto/MappedSearchForeignRequest.java, src/main/java/com/example/finalproject12be/domain/store/repository/StoreRepositoryCustom.java, src/main/java/com/example/finalproject12be/domain/store/service/StoreService.java
=> feat : 외국어 가능 매개변수 type 변경

src/main/java/com/example/finalproject12be/domain/comment/service/CommentService.java, src/main/java/com/example/finalproject12be/domain/store/controller/StoreController.java, src/main/java/com/example/finalproject12be/domain/store/dto/ForeignStoreResponse.java, src/main/java/com/example/finalproject12be/domain/store/dto/StoreResponseDto.java, src/main/java/com/example/finalproject12be/domain/store/entity/Store.java, src/main/java/com/example/finalproject12be/domain/store/entity/Store_1Case.java, src/main/java/com/example/finalproject12be/domain/store/repository/StoreRepositoryCustom.java, src/main/java/com/example/finalproject12be/domain/store/repository/StoreRepositoryCustom_1Case.java, src/main/java/com/example/finalproject12be/domain/store/service/StoreService.java
=> feat : queryDSL 로직 수정

src/main/java/com/example/finalproject12be/domain/store/repository/StoreRepositoryCustom.java, src/main/java/com/example/finalproject12be/domain/store/service/StoreService.java
- 필수 설정 조건을 설정하지 않을 시, 조회되는 결과 없음
=> feat : 필수 설정 조건 추가

src/main/java/com/example/finalproject12be/domain/store/dto/OneStoreResponseDto.java
"평일 nn:nn ~ nn:nn" -> "평일     nn:nn ~ nn:nn"
=> Refactor: 시간 반환 수정

src/main/java/com/example/finalproject12be/domain/store/dto/OneStoreResponseDto.java
"평일     nn:nn ~ nn:nn" -> "nn:nn ~ nn:nn"
=> Refactor: 시간 반환 재수정

src/main/java/com/example/finalproject12be/domain/store/controller/StoreController.java, src/main/java/com/example/finalproject12be/domain/store/dto/ForeignStoreResponse.java, src/main/java/com/example/finalproject12be/domain/store/entity/Store_3.java, src/main/java/com/example/finalproject12be/domain/store/entity/Store_3_language.java, src/main/java/com/example/finalproject12be/domain/store/repository/StoreRepositoryCustom.java, src/main/java/com/example/finalproject12be/domain/store/repository/StoreRepositoryCustom_2Case.java, src/main/java/com/example/finalproject12be/domain/store/service/StoreService.java
=> feat : 테스트를 위한 현재 시간 임의 조정
